# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20011Result(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, topic: str=None, username: str=None, team: str=None, sex: int=None, remarks: str=None):  # noqa: E501
        """InlineResponse20011Result - a model defined in Swagger

        :param id: The id of this InlineResponse20011Result.  # noqa: E501
        :type id: int
        :param topic: The topic of this InlineResponse20011Result.  # noqa: E501
        :type topic: str
        :param username: The username of this InlineResponse20011Result.  # noqa: E501
        :type username: str
        :param team: The team of this InlineResponse20011Result.  # noqa: E501
        :type team: str
        :param sex: The sex of this InlineResponse20011Result.  # noqa: E501
        :type sex: int
        :param remarks: The remarks of this InlineResponse20011Result.  # noqa: E501
        :type remarks: str
        """
        self.swagger_types = {
            'id': int,
            'topic': str,
            'username': str,
            'team': str,
            'sex': int,
            'remarks': str
        }

        self.attribute_map = {
            'id': 'id',
            'topic': 'topic',
            'username': 'username',
            'team': 'team',
            'sex': 'sex',
            'remarks': 'remarks'
        }

        self._id = id
        self._topic = topic
        self._username = username
        self._team = team
        self._sex = sex
        self._remarks = remarks

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20011Result':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_11_result of this InlineResponse20011Result.  # noqa: E501
        :rtype: InlineResponse20011Result
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse20011Result.

        user id  # noqa: E501

        :return: The id of this InlineResponse20011Result.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse20011Result.

        user id  # noqa: E501

        :param id: The id of this InlineResponse20011Result.
        :type id: int
        """

        self._id = id

    @property
    def topic(self) -> str:
        """Gets the topic of this InlineResponse20011Result.

        employee topic url  # noqa: E501

        :return: The topic of this InlineResponse20011Result.
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic: str):
        """Sets the topic of this InlineResponse20011Result.

        employee topic url  # noqa: E501

        :param topic: The topic of this InlineResponse20011Result.
        :type topic: str
        """

        self._topic = topic

    @property
    def username(self) -> str:
        """Gets the username of this InlineResponse20011Result.

        employee username  # noqa: E501

        :return: The username of this InlineResponse20011Result.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this InlineResponse20011Result.

        employee username  # noqa: E501

        :param username: The username of this InlineResponse20011Result.
        :type username: str
        """

        self._username = username

    @property
    def team(self) -> str:
        """Gets the team of this InlineResponse20011Result.

        team  # noqa: E501

        :return: The team of this InlineResponse20011Result.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team: str):
        """Sets the team of this InlineResponse20011Result.

        team  # noqa: E501

        :param team: The team of this InlineResponse20011Result.
        :type team: str
        """

        self._team = team

    @property
    def sex(self) -> int:
        """Gets the sex of this InlineResponse20011Result.

        employee sex  # noqa: E501

        :return: The sex of this InlineResponse20011Result.
        :rtype: int
        """
        return self._sex

    @sex.setter
    def sex(self, sex: int):
        """Sets the sex of this InlineResponse20011Result.

        employee sex  # noqa: E501

        :param sex: The sex of this InlineResponse20011Result.
        :type sex: int
        """

        self._sex = sex

    @property
    def remarks(self) -> str:
        """Gets the remarks of this InlineResponse20011Result.

        employee remarks  # noqa: E501

        :return: The remarks of this InlineResponse20011Result.
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks: str):
        """Sets the remarks of this InlineResponse20011Result.

        employee remarks  # noqa: E501

        :param remarks: The remarks of this InlineResponse20011Result.
        :type remarks: str
        """

        self._remarks = remarks
