# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body7(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, status: int=None, remarks: str=None):  # noqa: E501
        """Body7 - a model defined in Swagger

        :param id: The id of this Body7.  # noqa: E501
        :type id: int
        :param name: The name of this Body7.  # noqa: E501
        :type name: str
        :param status: The status of this Body7.  # noqa: E501
        :type status: int
        :param remarks: The remarks of this Body7.  # noqa: E501
        :type remarks: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'status': int,
            'remarks': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'status': 'status',
            'remarks': 'remarks'
        }

        self._id = id
        self._name = name
        self._status = status
        self._remarks = remarks

    @classmethod
    def from_dict(cls, dikt) -> 'Body7':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_7 of this Body7.  # noqa: E501
        :rtype: Body7
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Body7.

        user id  # noqa: E501

        :return: The id of this Body7.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Body7.

        user id  # noqa: E501

        :param id: The id of this Body7.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Body7.

        tment add  # noqa: E501

        :return: The name of this Body7.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Body7.

        tment add  # noqa: E501

        :param name: The name of this Body7.
        :type name: str
        """

        self._name = name

    @property
    def status(self) -> int:
        """Gets the status of this Body7.

        tment status  # noqa: E501

        :return: The status of this Body7.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Body7.

        tment status  # noqa: E501

        :param status: The status of this Body7.
        :type status: int
        """

        self._status = status

    @property
    def remarks(self) -> str:
        """Gets the remarks of this Body7.

        tment remarks  # noqa: E501

        :return: The remarks of this Body7.
        :rtype: str
        """
        return self._remarks

    @remarks.setter
    def remarks(self, remarks: str):
        """Sets the remarks of this Body7.

        tment remarks  # noqa: E501

        :param remarks: The remarks of this Body7.
        :type remarks: str
        """

        self._remarks = remarks
