# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20019PicList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, size: str=None, pic: str=None):  # noqa: E501
        """InlineResponse20019PicList - a model defined in Swagger

        :param size: The size of this InlineResponse20019PicList.  # noqa: E501
        :type size: str
        :param pic: The pic of this InlineResponse20019PicList.  # noqa: E501
        :type pic: str
        """
        self.swagger_types = {
            'size': str,
            'pic': str
        }

        self.attribute_map = {
            'size': 'size',
            'pic': 'pic'
        }

        self._size = size
        self._pic = pic

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20019PicList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_19_picList of this InlineResponse20019PicList.  # noqa: E501
        :rtype: InlineResponse20019PicList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> str:
        """Gets the size of this InlineResponse20019PicList.

        pic lenght  # noqa: E501

        :return: The size of this InlineResponse20019PicList.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this InlineResponse20019PicList.

        pic lenght  # noqa: E501

        :param size: The size of this InlineResponse20019PicList.
        :type size: str
        """

        self._size = size

    @property
    def pic(self) -> str:
        """Gets the pic of this InlineResponse20019PicList.

        pic data  # noqa: E501

        :return: The pic of this InlineResponse20019PicList.
        :rtype: str
        """
        return self._pic

    @pic.setter
    def pic(self, pic: str):
        """Sets the pic of this InlineResponse20019PicList.

        pic data  # noqa: E501

        :param pic: The pic of this InlineResponse20019PicList.
        :type pic: str
        """

        self._pic = pic
