# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005Userinfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, normal: int=None, late: int=None, retreat: int=None):  # noqa: E501
        """InlineResponse2005Userinfo - a model defined in Swagger

        :param username: The username of this InlineResponse2005Userinfo.  # noqa: E501
        :type username: str
        :param normal: The normal of this InlineResponse2005Userinfo.  # noqa: E501
        :type normal: int
        :param late: The late of this InlineResponse2005Userinfo.  # noqa: E501
        :type late: int
        :param retreat: The retreat of this InlineResponse2005Userinfo.  # noqa: E501
        :type retreat: int
        """
        self.swagger_types = {
            'username': str,
            'normal': int,
            'late': int,
            'retreat': int
        }

        self.attribute_map = {
            'username': 'username',
            'normal': 'normal',
            'late': 'late',
            'retreat': 'retreat'
        }

        self._username = username
        self._normal = normal
        self._late = late
        self._retreat = retreat

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005Userinfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5_userinfo of this InlineResponse2005Userinfo.  # noqa: E501
        :rtype: InlineResponse2005Userinfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this InlineResponse2005Userinfo.

        username  # noqa: E501

        :return: The username of this InlineResponse2005Userinfo.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this InlineResponse2005Userinfo.

        username  # noqa: E501

        :param username: The username of this InlineResponse2005Userinfo.
        :type username: str
        """

        self._username = username

    @property
    def normal(self) -> int:
        """Gets the normal of this InlineResponse2005Userinfo.

        normal  # noqa: E501

        :return: The normal of this InlineResponse2005Userinfo.
        :rtype: int
        """
        return self._normal

    @normal.setter
    def normal(self, normal: int):
        """Sets the normal of this InlineResponse2005Userinfo.

        normal  # noqa: E501

        :param normal: The normal of this InlineResponse2005Userinfo.
        :type normal: int
        """

        self._normal = normal

    @property
    def late(self) -> int:
        """Gets the late of this InlineResponse2005Userinfo.

        late  # noqa: E501

        :return: The late of this InlineResponse2005Userinfo.
        :rtype: int
        """
        return self._late

    @late.setter
    def late(self, late: int):
        """Sets the late of this InlineResponse2005Userinfo.

        late  # noqa: E501

        :param late: The late of this InlineResponse2005Userinfo.
        :type late: int
        """

        self._late = late

    @property
    def retreat(self) -> int:
        """Gets the retreat of this InlineResponse2005Userinfo.

        Leave early  # noqa: E501

        :return: The retreat of this InlineResponse2005Userinfo.
        :rtype: int
        """
        return self._retreat

    @retreat.setter
    def retreat(self, retreat: int):
        """Sets the retreat of this InlineResponse2005Userinfo.

        Leave early  # noqa: E501

        :param retreat: The retreat of this InlineResponse2005Userinfo.
        :type retreat: int
        """

        self._retreat = retreat
