# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response20016_morning import InlineResponse20016Morning  # noqa: F401,E501
from swagger_server import util


class InlineResponse20016(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, msg: str=None, morning: List[InlineResponse20016Morning]=None, afternoon: List[InlineResponse20016Morning]=None):  # noqa: E501
        """InlineResponse20016 - a model defined in Swagger

        :param code: The code of this InlineResponse20016.  # noqa: E501
        :type code: int
        :param msg: The msg of this InlineResponse20016.  # noqa: E501
        :type msg: str
        :param morning: The morning of this InlineResponse20016.  # noqa: E501
        :type morning: List[InlineResponse20016Morning]
        :param afternoon: The afternoon of this InlineResponse20016.  # noqa: E501
        :type afternoon: List[InlineResponse20016Morning]
        """
        self.swagger_types = {
            'code': int,
            'msg': str,
            'morning': List[InlineResponse20016Morning],
            'afternoon': List[InlineResponse20016Morning]
        }

        self.attribute_map = {
            'code': 'code',
            'msg': 'msg',
            'morning': 'morning',
            'afternoon': 'afternoon'
        }

        self._code = code
        self._msg = msg
        self._morning = morning
        self._afternoon = afternoon

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20016':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_16 of this InlineResponse20016.  # noqa: E501
        :rtype: InlineResponse20016
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse20016.

        system return code  # noqa: E501

        :return: The code of this InlineResponse20016.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse20016.

        system return code  # noqa: E501

        :param code: The code of this InlineResponse20016.
        :type code: int
        """

        self._code = code

    @property
    def msg(self) -> str:
        """Gets the msg of this InlineResponse20016.

        system return news  # noqa: E501

        :return: The msg of this InlineResponse20016.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this InlineResponse20016.

        system return news  # noqa: E501

        :param msg: The msg of this InlineResponse20016.
        :type msg: str
        """

        self._msg = msg

    @property
    def morning(self) -> List[InlineResponse20016Morning]:
        """Gets the morning of this InlineResponse20016.


        :return: The morning of this InlineResponse20016.
        :rtype: List[InlineResponse20016Morning]
        """
        return self._morning

    @morning.setter
    def morning(self, morning: List[InlineResponse20016Morning]):
        """Sets the morning of this InlineResponse20016.


        :param morning: The morning of this InlineResponse20016.
        :type morning: List[InlineResponse20016Morning]
        """

        self._morning = morning

    @property
    def afternoon(self) -> List[InlineResponse20016Morning]:
        """Gets the afternoon of this InlineResponse20016.


        :return: The afternoon of this InlineResponse20016.
        :rtype: List[InlineResponse20016Morning]
        """
        return self._afternoon

    @afternoon.setter
    def afternoon(self, afternoon: List[InlineResponse20016Morning]):
        """Sets the afternoon of this InlineResponse20016.


        :param afternoon: The afternoon of this InlineResponse20016.
        :type afternoon: List[InlineResponse20016Morning]
        """

        self._afternoon = afternoon
