# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response20021_pic import InlineResponse20021Pic  # noqa: F401,E501
from swagger_server import util


class MonitorPolling(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, camid: str=None, pic: List[InlineResponse20021Pic]=None):  # noqa: E501
        """MonitorPolling - a model defined in Swagger

        :param id: The id of this MonitorPolling.  # noqa: E501
        :type id: str
        :param camid: The camid of this MonitorPolling.  # noqa: E501
        :type camid: str
        :param pic: The pic of this MonitorPolling.  # noqa: E501
        :type pic: List[InlineResponse20021Pic]
        """
        self.swagger_types = {
            'id': str,
            'camid': str,
            'pic': List[InlineResponse20021Pic]
        }

        self.attribute_map = {
            'id': 'id',
            'camid': 'camid',
            'pic': 'pic'
        }

        self._id = id
        self._camid = camid
        self._pic = pic

    @classmethod
    def from_dict(cls, dikt) -> 'MonitorPolling':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MonitorPolling of this MonitorPolling.  # noqa: E501
        :rtype: MonitorPolling
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this MonitorPolling.

        id  # noqa: E501

        :return: The id of this MonitorPolling.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this MonitorPolling.

        id  # noqa: E501

        :param id: The id of this MonitorPolling.
        :type id: str
        """

        self._id = id

    @property
    def camid(self) -> str:
        """Gets the camid of this MonitorPolling.

        id  # noqa: E501

        :return: The camid of this MonitorPolling.
        :rtype: str
        """
        return self._camid

    @camid.setter
    def camid(self, camid: str):
        """Sets the camid of this MonitorPolling.

        id  # noqa: E501

        :param camid: The camid of this MonitorPolling.
        :type camid: str
        """

        self._camid = camid

    @property
    def pic(self) -> List[InlineResponse20021Pic]:
        """Gets the pic of this MonitorPolling.


        :return: The pic of this MonitorPolling.
        :rtype: List[InlineResponse20021Pic]
        """
        return self._pic

    @pic.setter
    def pic(self, pic: List[InlineResponse20021Pic]):
        """Sets the pic of this MonitorPolling.


        :param pic: The pic of this MonitorPolling.
        :type pic: List[InlineResponse20021Pic]
        """

        self._pic = pic
