# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2005_result import InlineResponse2005Result  # noqa: F401,E501
from swagger_server.models.inline_response2005_userinfo import InlineResponse2005Userinfo  # noqa: F401,E501
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, msg: str=None, userinfo: List[InlineResponse2005Userinfo]=None, result: List[InlineResponse2005Result]=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param code: The code of this InlineResponse2005.  # noqa: E501
        :type code: int
        :param msg: The msg of this InlineResponse2005.  # noqa: E501
        :type msg: str
        :param userinfo: The userinfo of this InlineResponse2005.  # noqa: E501
        :type userinfo: List[InlineResponse2005Userinfo]
        :param result: The result of this InlineResponse2005.  # noqa: E501
        :type result: List[InlineResponse2005Result]
        """
        self.swagger_types = {
            'code': int,
            'msg': str,
            'userinfo': List[InlineResponse2005Userinfo],
            'result': List[InlineResponse2005Result]
        }

        self.attribute_map = {
            'code': 'code',
            'msg': 'msg',
            'userinfo': 'userinfo',
            'result': 'result'
        }

        self._code = code
        self._msg = msg
        self._userinfo = userinfo
        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse2005.

        system return code  # noqa: E501

        :return: The code of this InlineResponse2005.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse2005.

        system return code  # noqa: E501

        :param code: The code of this InlineResponse2005.
        :type code: int
        """

        self._code = code

    @property
    def msg(self) -> str:
        """Gets the msg of this InlineResponse2005.

        system return news  # noqa: E501

        :return: The msg of this InlineResponse2005.
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg: str):
        """Sets the msg of this InlineResponse2005.

        system return news  # noqa: E501

        :param msg: The msg of this InlineResponse2005.
        :type msg: str
        """

        self._msg = msg

    @property
    def userinfo(self) -> List[InlineResponse2005Userinfo]:
        """Gets the userinfo of this InlineResponse2005.


        :return: The userinfo of this InlineResponse2005.
        :rtype: List[InlineResponse2005Userinfo]
        """
        return self._userinfo

    @userinfo.setter
    def userinfo(self, userinfo: List[InlineResponse2005Userinfo]):
        """Sets the userinfo of this InlineResponse2005.


        :param userinfo: The userinfo of this InlineResponse2005.
        :type userinfo: List[InlineResponse2005Userinfo]
        """

        self._userinfo = userinfo

    @property
    def result(self) -> List[InlineResponse2005Result]:
        """Gets the result of this InlineResponse2005.


        :return: The result of this InlineResponse2005.
        :rtype: List[InlineResponse2005Result]
        """
        return self._result

    @result.setter
    def result(self, result: List[InlineResponse2005Result]):
        """Sets the result of this InlineResponse2005.


        :param result: The result of this InlineResponse2005.
        :type result: List[InlineResponse2005Result]
        """

        self._result = result
