# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, team: int=None, mail: str=None, username: str=None, status: int=None, passwd: str=None):  # noqa: E501
        """Body1 - a model defined in Swagger

        :param id: The id of this Body1.  # noqa: E501
        :type id: int
        :param team: The team of this Body1.  # noqa: E501
        :type team: int
        :param mail: The mail of this Body1.  # noqa: E501
        :type mail: str
        :param username: The username of this Body1.  # noqa: E501
        :type username: str
        :param status: The status of this Body1.  # noqa: E501
        :type status: int
        :param passwd: The passwd of this Body1.  # noqa: E501
        :type passwd: str
        """
        self.swagger_types = {
            'id': int,
            'team': int,
            'mail': str,
            'username': str,
            'status': int,
            'passwd': str
        }

        self.attribute_map = {
            'id': 'id',
            'team': 'team',
            'mail': 'mail',
            'username': 'username',
            'status': 'status',
            'passwd': 'passwd'
        }

        self._id = id
        self._team = team
        self._mail = mail
        self._username = username
        self._status = status
        self._passwd = passwd

    @classmethod
    def from_dict(cls, dikt) -> 'Body1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_1 of this Body1.  # noqa: E501
        :rtype: Body1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Body1.

        user id  # noqa: E501

        :return: The id of this Body1.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Body1.

        user id  # noqa: E501

        :param id: The id of this Body1.
        :type id: int
        """

        self._id = id

    @property
    def team(self) -> int:
        """Gets the team of this Body1.

        team id  # noqa: E501

        :return: The team of this Body1.
        :rtype: int
        """
        return self._team

    @team.setter
    def team(self, team: int):
        """Sets the team of this Body1.

        team id  # noqa: E501

        :param team: The team of this Body1.
        :type team: int
        """

        self._team = team

    @property
    def mail(self) -> str:
        """Gets the mail of this Body1.

        login mail  # noqa: E501

        :return: The mail of this Body1.
        :rtype: str
        """
        return self._mail

    @mail.setter
    def mail(self, mail: str):
        """Sets the mail of this Body1.

        login mail  # noqa: E501

        :param mail: The mail of this Body1.
        :type mail: str
        """

        self._mail = mail

    @property
    def username(self) -> str:
        """Gets the username of this Body1.

        username  # noqa: E501

        :return: The username of this Body1.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Body1.

        username  # noqa: E501

        :param username: The username of this Body1.
        :type username: str
        """

        self._username = username

    @property
    def status(self) -> int:
        """Gets the status of this Body1.

        user status  # noqa: E501

        :return: The status of this Body1.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this Body1.

        user status  # noqa: E501

        :param status: The status of this Body1.
        :type status: int
        """

        self._status = status

    @property
    def passwd(self) -> str:
        """Gets the passwd of this Body1.

        login password  # noqa: E501

        :return: The passwd of this Body1.
        :rtype: str
        """
        return self._passwd

    @passwd.setter
    def passwd(self, passwd: str):
        """Sets the passwd of this Body1.

        login password  # noqa: E501

        :param passwd: The passwd of this Body1.
        :type passwd: str
        """

        self._passwd = passwd
