# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body15(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, status: str=None):  # noqa: E501
        """Body15 - a model defined in Swagger

        :param id: The id of this Body15.  # noqa: E501
        :type id: str
        :param status: The status of this Body15.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status'
        }

        self._id = id
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Body15':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_15 of this Body15.  # noqa: E501
        :rtype: Body15
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Body15.

        id  # noqa: E501

        :return: The id of this Body15.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Body15.

        id  # noqa: E501

        :param id: The id of this Body15.
        :type id: str
        """

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this Body15.

        status  # noqa: E501

        :return: The status of this Body15.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Body15.

        status  # noqa: E501

        :param status: The status of this Body15.
        :type status: str
        """

        self._status = status
