# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Login(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, passwd: str=None):  # noqa: E501
        """Login - a model defined in Swagger

        :param username: The username of this Login.  # noqa: E501
        :type username: str
        :param passwd: The passwd of this Login.  # noqa: E501
        :type passwd: str
        """
        self.swagger_types = {
            'username': str,
            'passwd': str
        }

        self.attribute_map = {
            'username': 'username',
            'passwd': 'passwd'
        }

        self._username = username
        self._passwd = passwd

    @classmethod
    def from_dict(cls, dikt) -> 'Login':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Login of this Login.  # noqa: E501
        :rtype: Login
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this Login.

        username  # noqa: E501

        :return: The username of this Login.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Login.

        username  # noqa: E501

        :param username: The username of this Login.
        :type username: str
        """

        self._username = username

    @property
    def passwd(self) -> str:
        """Gets the passwd of this Login.

        password  # noqa: E501

        :return: The passwd of this Login.
        :rtype: str
        """
        return self._passwd

    @passwd.setter
    def passwd(self, passwd: str):
        """Sets the passwd of this Login.

        password  # noqa: E501

        :param passwd: The passwd of this Login.
        :type passwd: str
        """

        self._passwd = passwd
