# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MonitorLists(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image: str=None):  # noqa: E501
        """MonitorLists - a model defined in Swagger

        :param image: The image of this MonitorLists.  # noqa: E501
        :type image: str
        """
        self.swagger_types = {
            'image': str
        }

        self.attribute_map = {
            'image': 'image'
        }

        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'MonitorLists':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MonitorLists of this MonitorLists.  # noqa: E501
        :rtype: MonitorLists
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> str:
        """Gets the image of this MonitorLists.

        image path  # noqa: E501

        :return: The image of this MonitorLists.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this MonitorLists.

        image path  # noqa: E501

        :param image: The image of this MonitorLists.
        :type image: str
        """

        self._image = image
