# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response20016_morning import InlineResponse20016Morning  # noqa: F401,E501
from swagger_server import util


class Body13(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, morning: List[InlineResponse20016Morning]=None, afternoon: List[InlineResponse20016Morning]=None):  # noqa: E501
        """Body13 - a model defined in Swagger

        :param morning: The morning of this Body13.  # noqa: E501
        :type morning: List[InlineResponse20016Morning]
        :param afternoon: The afternoon of this Body13.  # noqa: E501
        :type afternoon: List[InlineResponse20016Morning]
        """
        self.swagger_types = {
            'morning': List[InlineResponse20016Morning],
            'afternoon': List[InlineResponse20016Morning]
        }

        self.attribute_map = {
            'morning': 'morning',
            'afternoon': 'afternoon'
        }

        self._morning = morning
        self._afternoon = afternoon

    @classmethod
    def from_dict(cls, dikt) -> 'Body13':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_13 of this Body13.  # noqa: E501
        :rtype: Body13
        """
        return util.deserialize_model(dikt, cls)

    @property
    def morning(self) -> List[InlineResponse20016Morning]:
        """Gets the morning of this Body13.


        :return: The morning of this Body13.
        :rtype: List[InlineResponse20016Morning]
        """
        return self._morning

    @morning.setter
    def morning(self, morning: List[InlineResponse20016Morning]):
        """Sets the morning of this Body13.


        :param morning: The morning of this Body13.
        :type morning: List[InlineResponse20016Morning]
        """

        self._morning = morning

    @property
    def afternoon(self) -> List[InlineResponse20016Morning]:
        """Gets the afternoon of this Body13.


        :return: The afternoon of this Body13.
        :rtype: List[InlineResponse20016Morning]
        """
        return self._afternoon

    @afternoon.setter
    def afternoon(self, afternoon: List[InlineResponse20016Morning]):
        """Sets the afternoon of this Body13.


        :param afternoon: The afternoon of this Body13.
        :type afternoon: List[InlineResponse20016Morning]
        """

        self._afternoon = afternoon
