# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse20010Result(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, sex: str=None, team: str=None, status: int=None, posttime: str=None):  # noqa: E501
        """InlineResponse20010Result - a model defined in Swagger

        :param id: The id of this InlineResponse20010Result.  # noqa: E501
        :type id: int
        :param name: The name of this InlineResponse20010Result.  # noqa: E501
        :type name: str
        :param sex: The sex of this InlineResponse20010Result.  # noqa: E501
        :type sex: str
        :param team: The team of this InlineResponse20010Result.  # noqa: E501
        :type team: str
        :param status: The status of this InlineResponse20010Result.  # noqa: E501
        :type status: int
        :param posttime: The posttime of this InlineResponse20010Result.  # noqa: E501
        :type posttime: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'sex': str,
            'team': str,
            'status': int,
            'posttime': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'sex': 'sex',
            'team': 'team',
            'status': 'status',
            'posttime': 'posttime'
        }

        self._id = id
        self._name = name
        self._sex = sex
        self._team = team
        self._status = status
        self._posttime = posttime

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse20010Result':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_10_result of this InlineResponse20010Result.  # noqa: E501
        :rtype: InlineResponse20010Result
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse20010Result.

        ID  # noqa: E501

        :return: The id of this InlineResponse20010Result.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse20010Result.

        ID  # noqa: E501

        :param id: The id of this InlineResponse20010Result.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this InlineResponse20010Result.

        Account name  # noqa: E501

        :return: The name of this InlineResponse20010Result.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this InlineResponse20010Result.

        Account name  # noqa: E501

        :param name: The name of this InlineResponse20010Result.
        :type name: str
        """

        self._name = name

    @property
    def sex(self) -> str:
        """Gets the sex of this InlineResponse20010Result.

        employeel sex  # noqa: E501

        :return: The sex of this InlineResponse20010Result.
        :rtype: str
        """
        return self._sex

    @sex.setter
    def sex(self, sex: str):
        """Sets the sex of this InlineResponse20010Result.

        employeel sex  # noqa: E501

        :param sex: The sex of this InlineResponse20010Result.
        :type sex: str
        """

        self._sex = sex

    @property
    def team(self) -> str:
        """Gets the team of this InlineResponse20010Result.

        employeel team  # noqa: E501

        :return: The team of this InlineResponse20010Result.
        :rtype: str
        """
        return self._team

    @team.setter
    def team(self, team: str):
        """Sets the team of this InlineResponse20010Result.

        employeel team  # noqa: E501

        :param team: The team of this InlineResponse20010Result.
        :type team: str
        """

        self._team = team

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponse20010Result.

        employeel status  # noqa: E501

        :return: The status of this InlineResponse20010Result.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponse20010Result.

        employeel status  # noqa: E501

        :param status: The status of this InlineResponse20010Result.
        :type status: int
        """

        self._status = status

    @property
    def posttime(self) -> str:
        """Gets the posttime of this InlineResponse20010Result.

        Create time  # noqa: E501

        :return: The posttime of this InlineResponse20010Result.
        :rtype: str
        """
        return self._posttime

    @posttime.setter
    def posttime(self, posttime: str):
        """Sets the posttime of this InlineResponse20010Result.

        Create time  # noqa: E501

        :param posttime: The posttime of this InlineResponse20010Result.
        :type posttime: str
        """

        self._posttime = posttime
