# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AttendanceInfoList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, day: int=None, status: int=None):  # noqa: E501
        """AttendanceInfoList - a model defined in Swagger

        :param day: The day of this AttendanceInfoList.  # noqa: E501
        :type day: int
        :param status: The status of this AttendanceInfoList.  # noqa: E501
        :type status: int
        """
        self.swagger_types = {
            'day': int,
            'status': int
        }

        self.attribute_map = {
            'day': 'day',
            'status': 'status'
        }

        self._day = day
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'AttendanceInfoList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AttendanceInfoList of this AttendanceInfoList.  # noqa: E501
        :rtype: AttendanceInfoList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def day(self) -> int:
        """Gets the day of this AttendanceInfoList.

        day  # noqa: E501

        :return: The day of this AttendanceInfoList.
        :rtype: int
        """
        return self._day

    @day.setter
    def day(self, day: int):
        """Sets the day of this AttendanceInfoList.

        day  # noqa: E501

        :param day: The day of this AttendanceInfoList.
        :type day: int
        """

        self._day = day

    @property
    def status(self) -> int:
        """Gets the status of this AttendanceInfoList.

        Attendance status on the day  # noqa: E501

        :return: The status of this AttendanceInfoList.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this AttendanceInfoList.

        Attendance status on the day  # noqa: E501

        :param status: The status of this AttendanceInfoList.
        :type status: int
        """

        self._status = status
